feat(cli): add extractor witness gen
pluto/parser-attestor pull request #90
Opened 2024-09-11 19:47 UTC by lonerapier

2024-09-12 21:05 UTC, Autoparallel requested changes
Looks great! Can we add/edit docs to explain how to use the CLI more effectively? Best practices/etc.?

2024-09-12 21:05 UTC, Autoparallel commented on circuits/test/http/codegen.test.ts
> +        const codegen = spawn("cargo", ["run", "codegen", "http", "--circuit-name", circuitName, "--input-file", inputFilePath, "--lockfile", lockfilePath]);
good call

2024-09-12 21:05 UTC, Autoparallel commented on circuits/test/http/codegen.test.ts
> +        const codegen = spawn("cargo", ["run", "codegen", "http", "--circuit-name", circuitName, "--input-file", inputFilePath, "--lockfile", lockfilePath]);
Just seeing the usage here is helpful for sure

2024-09-12 21:07 UTC, Autoparallel commented
The CLI help menus you shared here are great! 

I'm gonna pull locally and mess around more. I might add/edit docs myself to carry this over.

2024-09-13 13:00 UTC, lonerapier commented
added updated docs with proof steps for both json and http

2024-09-13 18:28 UTC, Autoparallel approved these changes
Yes!! So good!

2024-09-13 18:28 UTC, merged